# Generated by Django 4.0.4 on 2022-05-07 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_company_alter_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='job',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='street2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='zip',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
