# Generated by Django 4.0.4 on 2022-05-07 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_summary_alter_job_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
