# Generated by Django 4.0.4 on 2022-05-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_city_alter_job_company_alter_job_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
    ]
